### ISSUE TITLE
Possible to support custom domain like *.<domain>?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/dns-release#2]
In our existing CF deployments, we are using powerDNS, we want to move to BOSH dns to mitigate the pain of SPoF of powerDNS. Currently, we added custom domains (point to haproxy or load balancer) in powerDNS, so that it can help route the requests, like api.<domain>, uaa.<domain>, <app>.<domain> and etc, to haproxy or load balancer. This is a very important requirement to us. Possible to support it in BOSH dns? Thanks.

/cc @maximilien @cppforlife

**Comment by cppforlife** [comment]
can you provide concrete example of these aliasing rules? ie what goes into matching and destination parts. that should help us make sure we would build right aliasing functionality.

**Comment by mattcui** [comment]
@cppforlife thanks for quick response, for example, if it's using haproxy in the deployment, I hope to add an alias like below:

```
addons:
- name: dns
  jobs:
  - name: dns
    release: dns
    properties:
      aliases:
        *.bosh-dns-sl-cpi.bluemix.net: [q-s0.ha-proxy.default.bosh-dns-sl-cpi.bosh]
```

So that api.bosh-dns-sl-cpi.bluemix.net, uaa.bosh-dns-sl-cpi.bluemix.net and (app).bosh-dns-sl-cpi.bluemix.net all can be routed to haproxy.

**Comment by cppforlife** [comment]
story: https://www.pivotaltracker.com/story/show/150418615

**Comment by mattcui** [comment]
Thanks, @cppforlife , I will give another try once this story is implemented.

/cc @maximilien

**Comment by mattcui** [comment]
Please note that the specific domain should overwrite wildcard domain, for examples:

```
addons:
- name: dns
  jobs:
  - name: dns
    release: dns
    properties:
      aliases:
        *.bosh-dns-sl-cpi.bluemix.net: [q-s0.ha-proxy.default.bosh-dns-sl-cpi.bosh]
        special_app.bosh-dns-sl-cpi.bluemix.net: [169.10.10.99]
```

Thanks.
