### ISSUE TITLE
Possible to provide APIs to CRUD bosh dns aliases?

### ISSUE THREAD

**Issue by gu-bin** [cloudfoundry/dns-release#21]
We have requirements to create new bosh dns aliases after the deployment is created. The current way is to add the aliases in the deployment manifest and run `bosh deploy` to update the whole deployment (thousands of vms) which is a big effort.
```
addons:
- name: dns
  jobs:
  - name: dns
    release: dns
    properties:
      aliases:
        a.bosh-dns-sl-cpi.bluemix.net: [169.10.10.88]
        b.bosh-dns-sl-cpi.bluemix.net: [169.10.10.99]     <-- new alias
```

Is it possible to provide APIs to create, retrieve, update and delete bosh dns aliases? In this way, bosh director can help synchronize the new bosh dns alias to all the vms just like the bosh native dns and no need to run `bosh deploy` to update the whole deployment.

/cc @mattcui
